# Generated by Django 3.2.6 on 2021-08-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='exp_date',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
