# Generated by Django 3.2.7 on 2021-09-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
